# Generated by Django 5.0.1 on 2024-02-29 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muscleforge', '0002_alter_exercise_description_alter_workoutplan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseinsession',
            name='duration',
        ),
    ]
