# Generated by Django 5.0.1 on 2024-03-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muscleforge', '0003_remove_exerciseinsession_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
