# Generated by Django 5.0.1 on 2024-03-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscleforge', '0009_alter_goal_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
